# Generated by Django 4.0.4 on 2022-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_and_motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=100)),
                ('horses', models.IntegerField()),
                ('release_date', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=100)),
                ('cylinder', models.IntegerField()),
                ('release_date', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='mortorcycle',
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
