# Generated by Django 4.0.4 on 2022-05-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_and_motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marque',
            new_name='car_marque',
        ),
        migrations.RemoveField(
            model_name='car',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='designer',
        ),
    ]
