# Generated by Django 4.0.3 on 2022-05-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_and_motorcycles', '0002_car_motorcycle_delete_mortorcycle_delete_voiture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='marque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_and_motorcycles.marque'),
        ),
    ]
